const mongoose = require('mongoose');

const eventSchema = new mongoose.Schema({
  sessionId: String,
  page: String,
  type: String,
  timestamp: Number,
  duration: Number,
  lastVisitedTime: String,
  element: String,
  userAgent: String,
  browserName: String,
  browserVersion: String,
  osName: String,
  platform: String,
  vendor: String,
  language: String,
  timezone: String,
  referrer: String,
  screenWidth: Number,
  screenHeight: Number,
  windowInnerWidth: Number,
  windowInnerHeight: Number,
  colorDepth: Number,
  pixelDepth: Number,
  deviceMemory: Number,
  hardwareConcurrency: Number,
  isTouchDevice: Boolean,
  isOnline: Boolean,
  saveData: Boolean,
  cookieEnabled: Boolean,
  jsHeapTotal: Number,
  jsHeapUsed: Number,
  networkType: String,
}, { timestamps: true });

module.exports = mongoose.model('Event7', eventSchema);
